### ISSUE TITLE
getting 404 on /.well-known/acme-challenge

### ISSUE THREAD

**Issue by p5ych0** [sandrokeil/docker-files#5]
hi
could you advise why this may happen when using your example image?

**Comment by sandrokeil** [comment]
Hello, have you read my [blog post about Let‘s Encrypt](https://sandro-keil.de/blog/openresty-nginx-with-auto-generated-ssl-certificate-from-lets-encrypt/)? It looks like some misconfiguration of the HTTP server definition.

**Comment by p5ych0** [comment]
yes, thanks.
my bad indeed ))
